Updated django-debug-toolbar to 1.5 to fix
TypeError at /
process() missing 1 required positional argument: 'stream'

Related to https://github.com/jazzband/django-debug-toolbar/issues/856